version: "3.7"
services:
  database:
    image: postgres:13
    container_name: postgres_database
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5433"
    volumes:
      - ./data:/var/lib/postgresql/data